### ISSUE TITLE
AttributeValueList.Deserialize - An item with the same key has already been added

### ISSUE THREAD

**Issue by J-ohn** [Eskat0n/Sphinx.Client#2]
Hello,

first of all I would like to thank you guys for Sphinx.Client. I have been using it for a couple of months without any issue, and the learning curve required is quite small.

After I upgraded sphinx to version 2.1.2-release I started getting some exceptions on queries that used to run fine. I see in your google project page (https://code.google.com/p/sphinx-dotnet-client/) that you support up to version 2.0.4 but I am not sure how updated that site is. 

I see in your comits that you have made some changes regarding the deserialization of attributes but I do not know if it applies to my case.

Thanks in advance and keep up the good work.

Stack trace:
 at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.ObjectModel.KeyedCollection`2.InsertItem(Int32 index, TItem item)
   at Sphinx.Client.Commands.Collections.AttributeValueList.Deserialize(IBinaryReader reader, MatchParseContext context)
   at Sphinx.Client.Commands.Search.Match.Deserialize(IBinaryReader reader, MatchParseContext context)
   at Sphinx.Client.Commands.Search.MatchList.Deserialize(IBinaryReader reader)
   at Sphinx.Client.Commands.Search.SearchQueryResult.Deserialize(IBinaryReader reader)
   at Sphinx.Client.Commands.Search.SearchCommandResult.Deserialize(IBinaryReader reader, Int32 count)
   at Sphinx.Client.Commands.Search.SearchCommand.DeserializeResponse(IBinaryReader reader)
   at Sphinx.Client.Commands.CommandWithResultBase`1.Deserialize(IStreamAdapter stream)
   at Sphinx.Client.Connections.TcpConnection.PerformCommand(CommandBase command)
   at Sphinx.Client.Commands.CommandBase.Execute()
   at Sphinx.Client.Commands.CommandWithResultBase`1.Execute()

**Comment by J-ohn** [comment]
Apparently adding 
if (Contains(attribute.Name))
 {
continue;
}
in AttributeValueList.Deserialize does the trick.
